### ISSUE TITLE
Consider using Pipenv or Poetry lock file

### ISSUE THREAD

**Issue by Kilo59** [tonybaloney/wily#25]
Both [Poetry](https://github.com/sdispater/poetry) and [Pipenv](https://pipenv.readthedocs.io/en/latest/) allow for a python equivalent of a Ruby/NPM lock file.

Using one of these tools to generate a lockfile for wily should make it easier for contributors to reproduce the same development environment and have a better awareness of the projects' dependency tree.

I'm more familiar with Pipenv than Poetry but one benefit of Poetry is that it already works nicely with `pyproject.toml` and the so the Lockfile would be the only new file that would need to be tracked.

With Pipenv we would need a `Pipfile` and ` Pipfiel.lock` and the Pipfile would duplicate what's in the requires section of the `pyproject.toml`

**Comment by tonybaloney** [comment]
At present I’m using flit to manage the build process instead of Poetry. All of the requirements for both building and installing are in pyproject.toml.

To install a develop version, you can run `flit install` (after adding flit to the virtual env and activating it). It should pull and install the correct dependencies.

With respect to the specific versions, Pipfile.lock is specific to a specific environment from my understanding, this package supports a few (Windows, Mac, Linux) and also Python 3.6-3.7. The built packages are different across platforms, for example it will have some extra color log package for Windows to support the colorful messages. Python 3.6 will download + install the dataclasses package.

Brett Cannon did a good explanation 
https://testandcode.com/52

From what I’ve seen this is one of relatively few packages to entirely use pyproject.toml 
https://pythonbytes.fm/episodes/show/104/api-evolution-the-right-way

If you did install + build this locally, I did fail to explain in the README that you need to install Flit and how to develop against this package
